### PR TITLE
Better comments and errors

### PR DESCRIPTION
**Pull request by tcarrondo**

### CODE REVIEW

**Review by abacao — APPROVED** [review]
LGTM but I still suggests a different name to the new-creds based on date of creation. Using a .new-creds already exists, what happens?

**Comment by tcarrondo** [comment]
@abacao that's just a temp file, always deleted and the end of each run.

**Comment by abacao** [comment]
I know. What happens if the file already exists?

**Comment by tcarrondo** [comment]
Bingo! I'll generate a random filename and, to play safe, try to remove it at the beginning of each run.

**Comment by abacao** [comment]
I would suggest to create a random filename in each run, store it to a temp variable and delete it in the end :grinning:

**Comment by tcarrondo** [comment]
Aren't we saying the same?

**Comment by tcarrondo** [comment]
#3

**Pull request merged**
